services:
  - type: web
    name: picupapp
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: >
      gunicorn mysite.wsgi:application
        --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: picupapp-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: picupapp.onrender.com,.mypicupapp.com,127.0.0.1,localhost,mypicupapp.com,www.mypicupapp.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://picupapp.onrender.com,https://mypicupapp.com,https://www.mypicupapp.com
      - key: GS_BUCKET_NAME
        value: mypicupapp-photos
      - key: GS_CREDENTIAL_JSON
        value: ${your_json_escaped_here}  # Replace with actual JSON string or use Render Secret File

  - type: static
    name: picupapp-static
    env: static
    staticPublishPath: staticfiles
    buildCommand: ""
    routes:
      - type: rewrite
        source: /static/(.*)
        destination: /$1

  - type: pserv
    name: picupapp-db
    env: postgres
    plan: free
