services:
  - type: web
    name: picupapp
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: picupapp-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "picupapp.onrender.com,.mypicupapp.com,127.0.0.1,127.0.0.1:8080,localhost:8080,localhost,mypicupapp-270799429435.us-west1.run.app,mypicupapp.com,www.mypicupapp.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://picupapp.onrender.com,https://mypicupapp.com,https://www.mypicupapp.com,https://mypicupapp-270799429435.us-west1.run.app"

  - type: static
    name: picupapp-static
    env: static
    buildCommand: ""
    staticPublishPath: staticfiles
    routes:
      - type: rewrite
        source: /static/(.*)
        destination: /$1

  - type: pserv
    name: picupapp-db
    env: postgres
    plan: free
