services:
  - type: web
    name: picupapp
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: picupapp-db
          property: connectionString

  - type: pserv
    name: picupapp-db
    env: postgres
    plan: free
