# Generated by Django 5.2.1 on 2025-05-11 14:50

import django.db.models.deletion
import picupapp.models
import picupapp.storage_backends
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('picupapp', '0001_initial'), ('picupapp', '0002_alter_photoupload_image'), ('picupapp', '0003_photoupload_comment_photoupload_latitude_and_more'), ('picupapp', '0004_photoupload_photo_taken_date'), ('picupapp', '0005_photoupload_visibility_alter_photoupload_image_and_more'), ('picupapp', '0006_photoupload_shared_with_alter_photogroup_name')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='photo_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=picupapp.storage_backends.PublicGoogleCloudStorage(), upload_to=picupapp.models.user_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo_taken_date', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('any', 'Any User'), ('group', 'Group')], default='private', max_length=10)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='picupapp.photogroup')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
