# Generated by Django 5.1.5 on 2025-05-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picupapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoupload',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
