# Generated by Django 5.1.5 on 2025-05-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picupapp', '0002_alter_photoupload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoupload',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='photoupload',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photoupload',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
