# Generated by Django 5.1.5 on 2025-05-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picupapp', '0003_photoupload_comment_photoupload_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoupload',
            name='photo_taken_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
