# Generated by Django 5.2.1 on 2025-05-11 06:40

import django.db.models.deletion
import picupapp.models
import picupapp.storage_backends
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picupapp', '0004_photoupload_photo_taken_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photoupload',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('any', 'Any User'), ('group', 'Group')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='photoupload',
            name='image',
            field=models.ImageField(storage=picupapp.storage_backends.PublicGoogleCloudStorage(), upload_to=picupapp.models.user_directory_path),
        ),
        migrations.CreateModel(
            name='PhotoGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='photo_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='photoupload',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='picupapp.photogroup'),
        ),
    ]
