# Generated by Django 5.2.1 on 2025-05-11 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picupapp', '0005_photoupload_visibility_alter_photoupload_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photoupload',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photogroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
